pipeline {
    agent any

    stages {
       stage('package') {
            steps {
              dir('ViQuJob') {
                bat 'mvn clean compile package'
              }
            }
        }
        stage('test') {
            steps {
              dir('ViQuJob') {
                bat 'mvn clean compile test'
              }
            }
        }
    }
}
