pipeline {
    agent any

     environment {
        SPRING_DATABASE_URL = "jdbc:postgresql://localhost:5432/hola"
        SPRING_USERNAME = "root"
        SPRING_PASSWORD = "password"
      }

    stages {
      
       stage('clean') {
            steps {
              dir('ViQuJob') {
                bat 'mvn clean compile package'
              }
            }
        }
        stage('compile') {
            steps {
              dir('ViQuJob') {
                bat 'mvn compile'
              }
            }
        }
        stage('package') {
            steps {
              dir('ViQuJob') {
                bat 'mvn package -DskipTests'
              }
            }
        }
        stage('test') {
            steps {
              dir('ViQuJob') {
                bat 'mvn test'
              }
            }
        }
        stage('deploy') {
          steps {
            withCredentials([usernamePassword(credentialsId:'dockerid',usernameVariable:'USR',passwordVariable:'PWD')])
              {
                  bat "heroku login -u=${env.USR} -p=${env.PWD}"
              }
              bat "git add ."
              bat "git commit -m 'deploy'"
              bat "git push heroku master"
          }
      }
    }
}
