pipeline {
    agent any

     environment {
        SPRING_DATABASE_URL = "jdbc:postgresql://localhost:5432/hola"
        SPRING_USERNAME = "root"
        SPRING_PASSWORD = "password"
      }

    stages {
      stage('deploy') {
        steps {
          bat "heroku login -i lucianolopez4000@hotmail.com polerro123@"
        }
      }
       stage('clean') {
            steps {
              dir('ViQuJob') {
                bat 'mvn clean compile package'
              }
            }
        }
        stage('compile') {
            steps {
              dir('ViQuJob') {
                bat 'mvn compile'
              }
            }
        }
        stage('package') {
            steps {
              dir('ViQuJob') {
                bat 'mvn package -DskipTests'
              }
            }
        }
        stage('test') {
            steps {
              dir('ViQuJob') {
                bat 'mvn test'
              }
            }
        }
    }
}
